# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8686d4b38ab8912b2901dd8c77d41da78e9a7f59ecbd146a5023c54ce5f51c371efa44fd64f58c1fa14e7f8309086115d1eb3ee66fb5ba0803bcae2e7dba2f74

test:
  secret_key_base: bd3b15b33b1cce7ee01107aa21f98ef32217bf2ac7264de2182ac022e0e5230f8c0a6bb2f866b8ec81316342db2547a26209ef9796580a285d1a8d865a842b93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
